autoclip: false
autoimport: false
cliptimeout: 45
exportkeys: true
nopager: false
notifications: true
parsing: false
path: /home/cwr/.local/share/gopass/stores/root
safecontent: false
mounts:
    readonly: /home/cwr/.local/share/gopass/stores/readonly
    technik: /home/cwr/.local/share/gopass/stores/technik
    technik-entwicklung: /home/cwr/.local/share/gopass/stores/technik-entwicklung
