#!/usr/bin/env bash

for service in 'polybar*.service' 'glava.target'; do
  if systemctl --user is-active "$service"; then
    systemctl --user restart "$service"
  fi
done

systemctl --user start feh
