#!/usr/bin/env bash

set -x

# don't trigger on systemd reloading, and triggering, udev rules 🤦
if sudo journalctl --since=1m | grep -q 30-systemd-udev-reload.hook; then
  exit 0
fi

services=( feh.service polybar.slice glava.target xorg-settings.service easyeffects.service )

systemctl --user reset-failed "${services[@]}"
systemctl --user try-reload-or-restart "${services[@]}"
