#!/usr/bin/env bash

for service in 'polybar.target' 'glava.target'; do
  if systemctl --user is-active "$service"; then
    systemctl --user restart "$service" &
  fi
done

systemctl --user restart feh &
wait
