#!/usr/bin/env bash
userresources=$XDG_CONFIG_HOME/xorg/.Xresources
usermodmap=$XDG_CONFIG_HOME/xorg/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if lsmod | grep -q nvidia; then
  xrandr --setprovideroutputsource modesetting NVIDIA-0
fi

mapfile -t detectedProfiles < <(autorandr --skip-options gamma,brightness --detected)

if [[ ${detectedProfiles[@]} =~ home ]]; then
  autorandr --load home
elif [[ ${detectedProfiles[@]} =~ work-k8s-window-left ]]; then
  autorandr --load work-k8s-window-left
else
  autorandr --load laptop
fi

systemd-cat --stderr-priority=warning --identifier=i3 nice -n -15 i3
#systemd-cat --stderr-priority=warning --identifier=xmonad nice -n -15 xmonad
systemctl --user stop --wait graphical-session.target
